const CONFIG={SPREADSHEET_ID:'',SHEET_INVOICE:'INVOICE',SHEET_DETAIL:'INVOICE_DETAIL',SHEET_CUSTOMER:'CUSTOMER',SHEET_SETTINGS:'SETTINGS',SHEET_PAYMENT:'PAYMENT',SHEET_PRODUCT:'PRODUCT',SHEET_STOCK:'STOCK_MOVEMENT',SHEET_PURCHASE:'PURCHASE',SHEET_PURCHASE_DETAIL:'PURCHASE_DETAIL'};
function ss(){return CONFIG.SPREADSHEET_ID?SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID):SpreadsheetApp.getActiveSpreadsheet();}
function getSheet(n){const s=ss().getSheetByName(n);if(!s)throw new Error('Sheet '+n+' tidak ditemukan.');return s;}
function ensureSheet(n,h){let s=ss().getSheetByName(n);if(!s){s=ss().insertSheet(n);s.appendRow(h);}return s;}
function ensurePaymentSheet(){return ensureSheet(CONFIG.SHEET_PAYMENT,['Payment ID','Invoice No','Tanggal','Jumlah','Metode Pembayaran','Catatan']);}
function ensureProductSheet(){return ensureSheet(CONFIG.SHEET_PRODUCT,['Product ID','Kode Produk','Nama Produk','Kategori','Satuan','Harga Beli','Harga Jual','Stok','Minimum Stok','Supplier','Aktif']);}
function ensureStockSheet(){return ensureSheet(CONFIG.SHEET_STOCK,['Movement ID','Tanggal','Product ID','Kode Produk','Nama Produk','Tipe','Qty','Referensi','Catatan']);}
function ensurePurchaseSheet(){return ensureSheet(CONFIG.SHEET_PURCHASE,['Purchase No','Tanggal','Supplier','No Faktur Supplier','Total','Catatan']);}
function ensurePurchaseDetailSheet(){return ensureSheet(CONFIG.SHEET_PURCHASE_DETAIL,['Purchase No','No','Product ID','Kode Produk','Nama Produk','Qty','Harga Beli','Total']);}
function doGet(e){try{const a=e&&e.parameter&&e.parameter.action;if(a==='getInitialData')return jsonResponse(getInitialData());if(a==='getInvoices')return jsonResponse({success:true,invoices:getInvoices()});if(a==='getInvoice')return jsonResponse(getInvoice(e.parameter.invoiceNo));if(a==='getPayments')return jsonResponse({success:true,payments:getPayments(e.parameter.invoiceNo)});if(a==='getDashboard')return jsonResponse(getDashboard());if(a==='getPurchase')return jsonResponse(getPurchase(e.parameter.purchaseNo));if(a==='getPurchases')return jsonResponse({success:true,purchases:getPurchases()});return jsonResponse({success:true,app:'SWA / Strato Business Manager API',version:'4.0.0',message:'API is running'});}catch(err){return jsonResponse({success:false,message:err.message||'Server error'});}}
function doPost(e){try{const d=JSON.parse(e.postData.contents||'{}');switch(d.action){case'getInitialData':return jsonResponse(getInitialData());case'getInvoices':return jsonResponse({success:true,invoices:getInvoices()});case'getInvoice':return jsonResponse(getInvoice(d.invoiceNo));case'saveInvoice':return jsonResponse(saveInvoice(d.invoice));case'recordPayment':return jsonResponse(recordPayment(d.payment));case'getPayments':return jsonResponse({success:true,payments:getPayments(d.invoiceNo)});case'updateStatus':return jsonResponse(updateStatus(d.invoiceNo,d.status));case'addCustomer':return jsonResponse(addCustomer(d.customer));case'updateCustomer':return jsonResponse(updateCustomer(d.customer));case'addProduct':return jsonResponse(addProduct(d.product));case'updateProduct':return jsonResponse(updateProduct(d.product));case'adjustStock':return jsonResponse(adjustStock(d.movement));case'getDashboard':return jsonResponse(getDashboard());case'savePurchase':return jsonResponse(savePurchase(d.purchase));case'getPurchase':return jsonResponse(getPurchase(d.purchaseNo));case'getPurchases':return jsonResponse({success:true,purchases:getPurchases()});default:return jsonResponse({success:false,message:'Unknown action: '+d.action});}}catch(err){console.error(err);return jsonResponse({success:false,message:err.message||'Server error'});}}
function jsonResponse(d){return ContentService.createTextOutput(JSON.stringify(d)).setMimeType(ContentService.MimeType.JSON);}
function getInitialData(){ensurePaymentSheet();ensureProductSheet();ensureStockSheet();ensurePurchaseSheet();ensurePurchaseDetailSheet();return{success:true,version:'4.0.0',customers:getCustomers(),invoices:getInvoices(),settings:getSettings(),products:getProducts(),purchases:getPurchases(),dashboard:getDashboard().dashboard};}
function getCustomers(){const v=getSheet(CONFIG.SHEET_CUSTOMER).getDataRange().getValues();return v.length<=1?[]:v.slice(1).filter(r=>r[0]!==''&&r[0]!=null).map(r=>({id:String(r[0]||''),name:String(r[1]||''),phone:String(r[2]||''),email:String(r[3]||''),address:String(r[4]||'')}));}
function getSettings(){const v=getSheet(CONFIG.SHEET_SETTINGS).getDataRange().getValues(),o={};v.slice(1).forEach(r=>{const k=String(r[0]||'').trim();if(k)o[k]=r[1]==null?'':r[1];});return o;}
function getProducts(){const v=ensureProductSheet().getDataRange().getValues();return v.length<=1?[]:v.slice(1).filter(r=>r[0]!==''&&r[0]!=null).map(r=>({id:String(r[0]),code:String(r[1]||''),name:String(r[2]||''),category:String(r[3]||''),unit:String(r[4]||'pcs'),buyPrice:Number(r[5]||0),sellPrice:Number(r[6]||0),stock:Number(r[7]||0),minStock:Number(r[8]||0),supplier:String(r[9]||''),active:String(r[10]).toLowerCase()!=='false'}));}
function getInvoices(){const v=getSheet(CONFIG.SHEET_INVOICE).getDataRange().getValues();if(v.length<=1)return[];return v.slice(1).filter(r=>r[0]!==''&&r[0]!=null).map(r=>({invoiceNo:String(r[0]),date:formatDate(r[1]),customerId:String(r[2]||''),customer:String(r[3]||''),phone:String(r[4]||''),email:String(r[5]||''),address:String(r[6]||''),subtotal:Number(r[7]||0),taxPercent:Number(r[8]||0),tax:Number(r[9]||0),grandTotal:Number(r[10]||0),status:String(r[11]||'Draft'),paymentMethod:String(r[12]||''),notes:String(r[13]||''),paidAmount:getPaidAmount(String(r[0])),remainingAmount:0,grossProfit:getInvoiceProfit(String(r[0]))})).map(x=>{x.remainingAmount=Math.max(0,x.grandTotal-x.paidAmount);x.status=deriveStatus(x);return x;});}
function getInvoice(no){const i=getInvoices().find(x=>x.invoiceNo===String(no));if(!i)return{success:false,message:'Invoice tidak ditemukan: '+no};i.items=getInvoiceItems(no);i.payments=getPayments(no);i.paidAmount=getPaidAmount(no);i.remainingAmount=Math.max(0,i.grandTotal-i.paidAmount);i.grossProfit=getInvoiceProfit(no);i.realizedProfit=calculateRealizedProfit(i);return{success:true,...i};}
function getInvoiceItems(no){const v=getSheet(CONFIG.SHEET_DETAIL).getDataRange().getValues();return v.length<=1?[]:v.slice(1).filter(r=>String(r[0]||'')===String(no)).map(r=>({no:Number(r[1]||0),description:String(r[2]||''),qty:Number(r[3]||0),price:Number(r[4]||0),total:Number(r[5]||0),productId:String(r[6]||''),unitCost:Number(r[7]||0),cogs:Number(r[8]||0),profit:Number(r[9]||0)}));}
function getPayments(no){const v=ensurePaymentSheet().getDataRange().getValues();return v.length<=1?[]:v.slice(1).filter(r=>!no||String(r[1]||'')===String(no)).map(r=>({paymentId:String(r[0]||''),invoiceNo:String(r[1]||''),date:formatDate(r[2]),amount:Number(r[3]||0),method:String(r[4]||''),notes:String(r[5]||'')}));}
function getPaidAmount(no){return getPayments(no).reduce((s,p)=>s+Number(p.amount||0),0);}
function deriveStatus(i){const b=String(i.status||'Draft').toLowerCase();if(b==='cancelled')return'Cancelled';const t=Number(i.grandTotal||0),p=Number(i.paidAmount||0);if(t>0&&p>=t)return'Paid';if(p>0)return'Partially Paid';return b==='sent'?'Sent':b==='draft'?'Draft':'Unpaid';}
function saveInvoice(i){if(!i)throw new Error('Data invoice tidak ditemukan.');const sh=getSheet(CONFIG.SHEET_INVOICE),ds=getSheet(CONFIG.SHEET_DETAIL);let no=String(i.invoiceNo||'').trim()||generateInvoiceNumber();const items=Array.isArray(i.items)?i.items:[];if(!items.length)throw new Error('Invoice harus memiliki minimal 1 item.');let sub=0,profit=0;const rows=items.map((x,n)=>{const q=Number(x.qty)||0,p=Number(x.price)||0,t=q*p;const prod=findProduct(String(x.description||''));const cost=prod?Number(prod.buyPrice||0):Number(x.unitCost||0);const cogs=q*cost;const pr=t-cogs;sub+=t;profit+=pr;return[no,n+1,String(x.description||''),q,p,t,prod?prod.id:(x.productId||''),cost,cogs,pr];});const taxPct=Number(i.taxPercent)||0,tax=sub*taxPct/100,total=sub+tax;const vals=sh.getDataRange().getValues();let ex=-1;for(let n=1;n<vals.length;n++)if(String(vals[n][0])===no){ex=n+1;break;}const row=[no,parseDate(i.date),i.customerId||'',i.customer||'',i.phone||'',i.email||'',i.address||'',sub,taxPct,tax,total,i.status||'Draft',i.paymentMethod||'',i.notes||''];const isNew=ex<0;if(ex>0)sh.getRange(ex,1,1,14).setValues([row]);else sh.appendRow(row);const dv=ds.getDataRange().getValues();for(let n=dv.length-1;n>=1;n--)if(String(dv[n][0])===no)ds.deleteRow(n+1);ds.getRange(ds.getLastRow()+1,1,rows.length,10).setValues(rows);if(isNew)applyStockForInvoice(no,items);SpreadsheetApp.flush();return{success:true,message:'Invoice berhasil disimpan.',invoiceNo:no,subtotal:sub,taxPercent:taxPct,tax,grandTotal:total,grossProfit:profit};}
function findProduct(text){const q=String(text||'').toLowerCase();return getProducts().find(p=>p.name.toLowerCase()===q||p.code.toLowerCase()===q)||null;}
function getInvoiceProfit(no){return getInvoiceItems(no).reduce((s,x)=>s+Number(x.profit||((Number(x.price)||0)-(Number(x.unitCost)||0))*Number(x.qty||0),0),0);}
function calculateRealizedProfit(i){const sales=Number(i.grandTotal||0);return sales?Number(i.paidAmount||0)*Number(i.grossProfit||0)/sales:0;}
function applyStockForInvoice(no,items){items.forEach(x=>{const p=findProduct(x.description);if(p&&Number(x.qty)>0){const ns=Number(p.stock)-Number(x.qty);setProductStock(p.id,ns);logStock({date:new Date(),productId:p.id,code:p.code,name:p.name,type:'OUT',qty:Number(x.qty),reference:no,notes:'Penjualan POS/Invoice'});}});}
function setProductStock(id,stock){const sh=ensureProductSheet(),v=sh.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(id)){sh.getRange(i+1,8).setValue(Number(stock));return;}}
function recordPayment(p){if(!p)throw new Error('Data pembayaran tidak ditemukan.');const inv=getInvoice(p.invoiceNo);if(!inv.success)throw new Error(inv.message);if(inv.status==='Cancelled')throw new Error('Invoice dibatalkan.');const a=Number(p.amount)||0;if(a<=0)throw new Error('Jumlah pembayaran harus lebih dari 0.');if(a>inv.remainingAmount+.01)throw new Error('Pembayaran melebihi sisa tagihan.');const id=generatePaymentId();ensurePaymentSheet().appendRow([id,p.invoiceNo,parseDate(p.date),a,p.method||'Transfer Bank',p.notes||'']);const u=getInvoice(p.invoiceNo);return{success:true,message:'Pembayaran berhasil dicatat.',paymentId:id,invoiceNo:p.invoiceNo,paidAmount:u.paidAmount,remainingAmount:u.remainingAmount,status:u.status,grossProfit:u.grossProfit,realizedProfit:u.realizedProfit};}
function updateStatus(no,status){const sh=getSheet(CONFIG.SHEET_INVOICE),v=sh.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(no)){sh.getRange(i+1,12).setValue(status);return{success:true,message:'Status invoice diperbarui.',invoiceNo:no,status};}throw new Error('Invoice tidak ditemukan: '+no);}
function addCustomer(c){if(!c||!String(c.name||'').trim())throw new Error('Nama customer wajib diisi.');const sh=getSheet(CONFIG.SHEET_CUSTOMER),id=String(c.id||'').trim()||generateCustomerId();if(getCustomers().some(x=>x.id===id))throw new Error('Customer ID sudah digunakan.');sh.appendRow([id,c.name||'',c.phone||'',c.email||'',c.address||'']);return{success:true,message:'Customer berhasil ditambahkan.'};}
function updateCustomer(c){if(!c||!String(c.id||'').trim())throw new Error('Customer ID wajib.');const sh=getSheet(CONFIG.SHEET_CUSTOMER),v=sh.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(c.id)){sh.getRange(i+1,1,1,5).setValues([[c.id,c.name||'',c.phone||'',c.email||'',c.address||'']]);SpreadsheetApp.flush();return{success:true,message:'Customer diperbarui.'};}throw new Error('Customer tidak ditemukan: '+c.id);}
function addProduct(p){if(!p||!String(p.name||'').trim())throw new Error('Nama produk wajib diisi.');const sh=ensureProductSheet(),id=String(p.id||'').trim()||generateProductId();if(getProducts().some(x=>x.id===id||x.code===String(p.code||'')))throw new Error('Product ID atau kode produk sudah digunakan.');sh.appendRow([id,p.code||'',p.name||'',p.category||'',p.unit||'pcs',Number(p.buyPrice)||0,Number(p.sellPrice)||0,Number(p.stock)||0,Number(p.minStock)||0,p.supplier||'',p.active===false?'FALSE':'TRUE']);return{success:true,message:'Produk berhasil ditambahkan.'};}
function updateProduct(p){if(!p||!p.id)throw new Error('Product ID wajib.');const sh=ensureProductSheet(),v=sh.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(p.id)){const old=Number(v[i][7])||0,ns=Number(p.stock)||0;sh.getRange(i+1,1,1,11).setValues([[p.id,p.code||'',p.name||'',p.category||'',p.unit||'pcs',Number(p.buyPrice)||0,Number(p.sellPrice)||0,ns,Number(p.minStock)||0,p.supplier||'',p.active===false?'FALSE':'TRUE']]);if(ns!==old)logStock({date:new Date(),productId:p.id,code:p.code||'',name:p.name||'',type:ns>old?'IN':'ADJUST',qty:Math.abs(ns-old),reference:'EDIT',notes:'Penyesuaian stok'});return{success:true,message:'Produk diperbarui.'};}throw new Error('Produk tidak ditemukan.');}
function adjustStock(m){if(!m||!m.productId)throw new Error('Produk wajib dipilih.');const p=getProducts().find(x=>x.id===String(m.productId));if(!p)throw new Error('Produk tidak ditemukan.');const q=Number(m.qty)||0;if(q<=0)throw new Error('Qty harus lebih dari 0.');const d=m.type==='OUT'?-q:q,ns=Number(p.stock)+d;if(ns<0)throw new Error('Stok tidak cukup.');setProductStock(p.id,ns);logStock({date:parseDate(m.date),productId:p.id,code:p.code,name:p.name,type:m.type==='OUT'?'OUT':'IN',qty:q,reference:m.reference||'MANUAL',notes:m.notes||'Penyesuaian stok'});return{success:true,message:'Stok berhasil diperbarui.',stock:ns};}
function logStock(m){ensureStockSheet().appendRow([generateMovementId(),parseDate(m.date),m.productId,m.code,m.name,m.type,m.qty,m.reference||'',m.notes||'']);}
function getPurchases(){const v=ensurePurchaseSheet().getDataRange().getValues();return v.length<=1?[]:v.slice(1).filter(r=>r[0]!==''&&r[0]!=null).map(r=>({purchaseNo:String(r[0]),date:formatDate(r[1]),supplier:String(r[2]||''),reference:String(r[3]||''),total:Number(r[4]||0),notes:String(r[5]||'')}));}
function getPurchase(no){const p=getPurchases().find(x=>x.purchaseNo===String(no));if(!p)return{success:false,message:'Pembelian tidak ditemukan: '+no};const v=ensurePurchaseDetailSheet().getDataRange().getValues();p.items=v.length<=1?[]:v.slice(1).filter(r=>String(r[0])===String(no)).map(r=>({no:Number(r[1]||0),productId:String(r[2]||''),code:String(r[3]||''),productName:String(r[4]||''),qty:Number(r[5]||0),unitCost:Number(r[6]||0),total:Number(r[7]||0)}));return{success:true,...p};}
function savePurchase(p){if(!p)throw new Error('Data pembelian tidak ditemukan.');const items=Array.isArray(p.items)?p.items:[];if(!items.length)throw new Error('Pembelian harus memiliki minimal 1 item.');const ps=ensurePurchaseSheet(),ds=ensurePurchaseDetailSheet(),no=String(p.purchaseNo||'').trim()||generatePurchaseNumber();let total=0;const rows=[];items.forEach((x,i)=>{const prod=getProducts().find(a=>a.id===String(x.productId));if(!prod)throw new Error('Produk tidak ditemukan: '+x.productId);const q=Number(x.qty)||0,c=Number(x.unitCost)||0;if(q<=0||c<0)throw new Error('Qty dan harga beli tidak valid untuk '+prod.name);const t=q*c;total+=t;rows.push([no,i+1,prod.id,prod.code,prod.name,q,c,t]);const oldStock=Number(prod.stock)||0,oldCost=Number(prod.buyPrice)||0,newStock=oldStock+q,newCost=newStock>0?((oldStock*oldCost)+(q*c))/newStock:c;setProductStock(prod.id,newStock);updateProductBuyPrice(prod.id,newCost);logStock({date:parseDate(p.date),productId:prod.id,code:prod.code,name:prod.name,type:'IN',qty:q,reference:no,notes:'Pembelian / Kulakan'});});ps.appendRow([no,parseDate(p.date),p.supplier||'',p.reference||'',total,p.notes||'']);ds.getRange(ds.getLastRow()+1,1,rows.length,8).setValues(rows);SpreadsheetApp.flush();return{success:true,message:'Pembelian berhasil disimpan.',purchaseNo:no,total};}
function updateProductBuyPrice(id,cost){const sh=ensureProductSheet(),v=sh.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(id)){sh.getRange(i+1,6).setValue(Number(cost));return;}}
function generatePurchaseNumber(){const y=new Date().getFullYear(),a=getPurchases();let m=0;a.forEach(x=>{const z=String(x.purchaseNo).match(/^PO-(\d+)-(\d+)$/);if(z&&Number(z[1])===y)m=Math.max(m,Number(z[2]));});return'PO-'+y+'-'+String(m+1).padStart(4,'0');}
function getDashboard(){const inv=getInvoices(),prod=getProducts(),purchases=getPurchases(),t=new Date(),month=t.getMonth()+1,year=t.getFullYear();const mi=inv.filter(x=>{const z=String(x.date);return z.endsWith('/'+year)&&Number(z.slice(3,5))===month;});const mp=purchases.filter(x=>{const z=String(x.date);return z.endsWith('/'+year)&&Number(z.slice(3,5))===month;});const sales=mi.reduce((s,x)=>s+x.grandTotal,0),paid=mi.reduce((s,x)=>s+x.paidAmount,0),outstanding=inv.reduce((s,x)=>s+x.remainingAmount,0),profit=inv.reduce((s,x)=>s+x.grossProfit,0),realized=inv.reduce((s,x)=>s+x.realizedProfit,0),low=prod.filter(x=>x.active&&x.stock<=x.minStock),top={};inv.forEach(i=>getInvoiceItems(i.invoiceNo).forEach(it=>{top[it.description]=(top[it.description]||0)+Number(it.qty||0);}));return{success:true,dashboard:{invoiceCount:inv.length,monthSales:sales,monthPaid:paid,monthPurchase:mp.reduce((s,x)=>s+x.total,0),outstanding,productCount:prod.filter(x=>x.active).length,lowStock:low.length,lowStockItems:low.slice(0,8),topProducts:Object.entries(top).sort((a,b)=>b[1]-a[1]).slice(0,5).map(x=>({name:x[0],qty:x[1]})),recentInvoices:inv.slice(-8).reverse(),grossProfit:profit,realizedProfit:realized}};}
function generateInvoiceNumber(){const s=getSettings(),pre=String(s['Prefix Invoice']||'INV'),y=new Date().getFullYear(),a=getInvoices();let m=0;a.forEach(x=>{const z=String(x.invoiceNo).match(new RegExp('^'+pre+'-'+y+'-(\\d+)$'));if(z)m=Math.max(m,Number(z[1]));});return pre+'-'+y+'-'+String(m+1).padStart(4,'0');}
function generatePaymentId(){let m=0;getPayments().forEach(x=>{const z=x.paymentId.match(/^PAY-(\d+)$/);if(z)m=Math.max(m,Number(z[1]));});return'PAY-'+String(m+1).padStart(4,'0');}
function generateCustomerId(){return'C'+String(getCustomers().length+1).padStart(3,'0');}function generateProductId(){return'P'+String(getProducts().length+1).padStart(4,'0');}function generateMovementId(){return'MOV-'+Utilities.getUuid().slice(0,8).toUpperCase();}
function parseDate(v){if(!v)return new Date();if(Object.prototype.toString.call(v)==='[object Date]')return v;const s=String(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s)){const p=s.split('-');return new Date(+p[0],+p[1]-1,+p[2]);}if(/^\d{2}\/\d{2}\/\d{4}$/.test(s)){const p=s.split('/');return new Date(+p[2],+p[1]-1,+p[0]);}const d=new Date(s);return isNaN(d.getTime())?new Date():d;}
function formatDate(v){if(!v)return'';const d=Object.prototype.toString.call(v)==='[object Date]'?v:new Date(v);if(isNaN(d.getTime()))return String(v);return String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear();}
